accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
]

crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

articles/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = '__all__'

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import get_user_model
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

# Create your views here.
def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = UserCreationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/signup.html', context)

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('articles:index')
    else:
        form = AuthenticationForm()
    context = {
        'form' : form
    }
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('articles:index')

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from .models import Article
from .forms import ArticleForm
# Create your views here.

def index(request):
    articles = Article.objects.order_by('-pk')
    context = {
        'articles': articles
    }
    return render(request, 'articles/index.html', context)

def create(request):
    # POST 일때
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        # 유효성 검사
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    # GET 일때, form을 보내준다.(처리)
    else:
        form = ArticleForm()
    context = {
        'form': form
    }
    return render(request, 'articles/create.html', context)

def detail(request, pk):
    article = get_object_or_404(Article, pk=pk)
    context = {
        'article': article
    }
    return render(request, 'articles/detail.html', context)

@require_POST
def delete(request, pk):
    article = get_object_or_404(Article, pk=pk)
    article.delete()
    return redirect('articles:index')

def update(request, pk):
    # 수정시에는 해당 instance를 넘겨줘야한다.
    article = get_object_or_404(Article, pk=pk)
    # 저장
    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            article = form.save()
            return redirect('articles:detail', article.pk)
    # 처리
    else:
        form = ArticleForm(instance=article)
    context = {
        'form': form
    }
    return render(request, 'articles/create.html', context)

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block body %}
<h1>LOGIN</h1>
<form action='' method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <button>로그인</button>
</form>
<button type="button" onclick="location.href='{% url 'accounts:signup' %}' ">회원가입</button>
<button type="button" onclick="location.href='{% url 'articles:index' %}' ">BACK</button>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block body %}
<h1>SIGN UP</h1><hr>
<form action='' method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button>회원가입</button>
</form>
<button type="button" onclick="location.href='{% url 'accounts:login' %}' ">로그인</button>
<button type="button" onclick="location.href='{% url 'articles:index' %}' ">BACK</button>
{% endblock %}

articles/templates/articles/create.html
{% extends 'base.html' %}

{% block body %}
{% if request.resolver_match.url_name == 'create' %}
    <h1>Create</h1>
{% else %}
    <h1>Update</h1>
{% endif %}
<form action="" method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <button>제출</button>
</form>
<button type="button" onclick="location.href='{% url 'articles:index' %}' ">BACK</button>
{% endblock %}

articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block body %}
<h1>DETAIL</h1>
<h2>{{ article.pk}}번 글</h2>
<h2>제목 : {{ article.title }}</h2>
<h3>내용 : {{ article.content }}</h2>
<h4>최초 등록 시간 : {{ article.created_at }}</h4>
<h4>글 수정 시간 : {{ article.updated_at }}</h4>
<form action="{% url 'articles:delete' article.pk %}" method='POST'>
    {% csrf_token %}
    <button>삭제</button>
</form>
<form action="{% url 'articles:update' article.pk %}">
    {% csrf_token %}
    <button>수정</button>
</form>
{% endblock %}

articles/templates/articles/index.html
{% extends 'base.html' %}

{% block body %}
<h1>INDEX</h1>
<a href="{% url 'articles:create' %}">글 쓰기</a>
{% for article in articles %}
<h2>{{ article.pk }}번째 글</h2>
<h2>{{ article.title }}</h2>
<a href="{% url 'articles:detail' article.pk %}">DETAIL</a>
<hr>
{% endfor %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>